name: UnicornMailbox
main: me.kapehh.UnicornMailbox.Main
author: kapehh
version: 1.0.0
commands:
    mailbox:
        usage: /<command> (send [player] | receiv | give [player] [chestname])
        description: UnicornMailbox
        aliases: mail